version: '3.1'

services:
  web:
    build: .
    command: nodemon --debug=5858
    ports:
     - "8080:8080"
     - "5858:5858"
    environment:
     - MONGO_HOST=mongo
    volumes:
     - .:/src
  mongo:
    image: mongo:latest
